export const translateRu = {
  gen: 'Бытие',
  exo: 'Исход',
  lev: 'Левит',
  num: 'Числа',
  deu: 'Второзаконие',
  jos: 'Иисус Навин',
  jdg: 'Судьи',
  rut: 'Руфь',
  '1sa': '1 Царств',
  '2sa': '2 Царств',
  '1ki': '3 Царств',
  '2ki': '4 Царств',
  '1ch': '1 Паралипоменон',
  '2ch': '2 Паралипоменон',
  ezr: 'Ездры',
  neh: 'Неемии',
  est: 'Есфирь',
  job: 'Иов',
  psa: 'Псалтирь',
  pro: 'Притчи',
  ecc: 'Екклесиаст',
  sng: 'Песнь Песней',
  isa: 'Исайя',
  jer: 'Иеремия',
  lam: 'Плач Иеремии',
  ezk: 'Иезекиль',
  dan: 'Даниил',
  hos: 'Осия',
  jol: 'Иоиль',
  amo: 'Амос',
  oba: 'Авдий',
  jon: 'Иона',
  mic: 'Михей',
  nam: 'Наум',
  hab: 'Аввакум',
  zep: 'Софония',
  hag: 'Аггей',
  zec: 'Захария',
  mal: 'Малахия',
  mat: 'Матфея',
  mrk: 'Марка',
  luk: 'Луки',
  jhn: 'Иоанна',
  act: 'Деяния',
  rom: 'Римлянам',
  '1co': '1 Коринфянам',
  '2co': '2 Коринфянам',
  gal: 'Галатам',
  eph: 'Ефесянам',
  php: 'Филлипийцам',
  col: 'Колоссянам',
  '1th': '1 Фессалоникийцам',
  '2th': '2 Фессалоникийцам',
  '1ti': '1 Тимофею',
  '2ti': '2 Тимофею',
  tit: 'Титу',
  phm: 'Филимону',
  heb: 'Евреям',
  jas: 'Иакова',
  '1pe': '1 Петра',
  '2pe': '2 Петра',
  '1jn': '1 Иоанна',
  '2jn': '2 Иоанна',
  '3jn': '3 Иоанна',
  jud: 'Иуды',
  rev: 'Откровение',
};

export const translateEn = {
  gen: 'Genesis',
  exo: 'Exodus',
  lev: 'Leviticus',
  num: 'Numbers',
  deu: 'Deuteronomy',
  jos: 'Joshua',
  jdg: 'Judges',
  rut: 'Ruth',
  '1sa': '1 Samuel',
  '2sa': '2 Samuel',
  '1ki': '1 Kings',
  '2ki': '2 Kings',
  '1ch': '1 Chronicles',
  '2ch': '2 Chronicles',
  ezr: 'Ezra',
  neh: 'Nehemiah',
  est: 'Esther',
  job: 'Job',
  psa: 'Psalms',
  pro: 'Proverbs',
  ecc: 'Ecclesiastes',
  sng: 'Song of Solomon',
  isa: 'Isaiah',
  jer: 'Jeremiah',
  lam: 'Lamentations',
  ezk: 'Ezekiel',
  dan: 'Daniel',
  hos: 'Hosea',
  jol: 'Joel',
  amo: 'Amos',
  oba: 'Obadiah',
  jon: 'Jonah',
  mic: 'Micah',
  nam: 'Nahum',
  hab: 'Habakkuk',
  zep: 'Zephaniah',
  hag: 'Haggai',
  zec: 'Zechariah',
  mal: 'Malachi',
  mat: 'Matthew',
  mrk: 'Mark',
  luk: 'Luke',
  jhn: 'John',
  act: 'Acts',
  rom: 'Romans',
  '1co': '1 Corinthians',
  '2co': '2 Corinthians',
  gal: 'Galatians',
  eph: 'Ephesians',
  php: 'Philippians',
  col: 'Colossians',
  '1th': '1 Thessalonians',
  '2th': '2 Thessalonians',
  '1ti': '1 Timothy',
  '2ti': '2 Timothy',
  tit: 'Titus',
  phm: 'Philemon',
  heb: 'Hebrews',
  jas: 'James',
  '1pe': '1 Peter',
  '2pe': '2 Peter',
  '1jn': '1 John',
  '2jn': '2 John',
  '3jn': '3 John',
  jud: 'Jude',
  rev: 'Revelation',
};

export const defaultBooks = {
  gen: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  exo: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  lev: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  num: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  deu: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jos: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jdg: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  rut: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1sa': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2sa': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1ki': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2ki': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1ch': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2ch': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  ezr: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  neh: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  est: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  job: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  psa: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  pro: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  ecc: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  sng: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  isa: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jer: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  lam: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  ezk: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  dan: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  hos: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jol: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  amo: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  oba: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jon: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  mic: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  nam: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  hab: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  zep: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  hag: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  zec: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  mal: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  mat: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  mrk: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  luk: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jhn: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  act: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  rom: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1co': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2co': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  gal: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  eph: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  php: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  col: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1th': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2th': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1ti': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2ti': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  tit: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  phm: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  heb: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jas: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1pe': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2pe': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '1jn': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '2jn': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  '3jn': { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  jud: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
  rev: { status: 'todo', chapters: 0, progress: 0, date_start: '', date_end: '', date_plan_end: '', date_plan_start: '' },
};

export const statusesRu = {
  todo: 'not started',
  progress: 'in rogress',
  done: 'done',
};
